# Generated by Django 2.0.5 on 2018-06-30 23:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlgorithmData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rec_count', models.IntegerField()),
                ('loop_n_depend', models.IntegerField()),
                ('loop_nested', models.IntegerField()),
                ('loop_type', models.IntegerField()),
                ('prog_terminate', models.IntegerField()),
                ('using_non_scalar', models.IntegerField()),
                ('repeat_values', models.IntegerField()),
                ('reuse_values', models.IntegerField()),
                ('complexity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainData',
            fields=[
                ('algorithmdata_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ab_ui.AlgorithmData')),
                ('classification', models.IntegerField(default=0)),
            ],
            bases=('ab_ui.algorithmdata',),
        ),
    ]
